CREATE TABLE users 
( id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
voted BOOLEAN DEFAULT FALSE );

CREATE TABLE candidates 
( id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE, 
votes INT DEFAULT 0 );

CREATE TABLE votes 
( id INT AUTO_INCREMENT PRIMARY KEY, 
user_id INT NOT NULL, 
candidate_id INT NOT NULL, 
vote_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, 
FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE );